### ISSUE TITLE
Bug when trying to upcast a delegate return type

### ISSUE THREAD

**Issue by israellot** [dynamicexpresso/DynamicExpresso#185]
```
var interpreter = new Interpreter().SetVariable("a", 123L);  
var del = interpreter.ParseAsDelegate<Func<object>>("a*2");
```

```
var interpreter = new Interpreter().SetVariable("a", 123L);  
var del = interpreter.ParseAsDelegate<Func<dynamic>>("a*2");
```
  
These simple examples used to run just fine on 2.8X and fails at 2.9.5.
I believe support to auto upcasting should be maintained.

**Comment by metoule** [comment]
Both examples worked with v2.8.1, but stopped working in v2.9.0, so it's linked to PR #140.
I'll investigate why it stopped working.

**Comment by metoule** [comment]
That was a side effect of the lambda expression support. 

Background: the parser is able to correctly detect the type of an expression, but it emits a conversion expression from the actual type to the requested return type (so here, `object`).

When parsing a lambda expression, the return type is not known beforehand, so we use `typeof(object)` by default. That's an issue, because while the actual type was properly detected by the parser, it was lost due to a forced conversion to `typeof(object)`. To prevent this, I no longer emitted the conversion expression if the return type was `object`, but that caused an issue if that's what's actually wanted!

To fix all this, when parsing a lambda expression, I now use `typeof(void)` to prevent the emission of the conversion expression.

**Comment by israellot** [comment]
Thanks @metoule ! I would go dig it myself and submit a PR later, but you were faster than me.
